<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\DTOs\" />
    <Folder Include="Common\Utility\" />
    <Folder Include="Mapping\" />
    <Folder Include="Common\Repository Interfaces\" />
    <Folder Include="Contract\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Services\Implementations\" />
  </ItemGroup>

</Project>
