@DainikBazar.WebApi_HostAddress = https://localhost:7155

GET {{DainikBazar.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DainikBazar.WebApi_HostAddress}}/api/products

###

GET {{DainikBazar.WebApi_HostAddress}}/api/products

###
